### ISSUE TITLE
WE NEED SUPPORT FOR FEDORA

### ISSUE THREAD

**Issue by Besufikad17** [cococry/Ragnar#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cococry** [comment]
what is your problem?

**Comment by Besufikad17** [comment]
I am having hard time building ragnar from source It would be cool if u add installation script

**Comment by chadcat7** [comment]
@cococry instead of making a install script, it would be better to include the x11 related and other general dependencies in the readme to help users on other distros!

**Comment by Besufikad17** [comment]
> A proper list of dependencies has been added to the README. Thanks for pointing this out

![image](https://github.com/cococry/Ragnar/assets/64811433/082a5499-eaeb-4864-b813-877ced3f2cbb)
I installed xorg and xorg dependencies as listed in readme but i am getting this error
