### ISSUE TITLE
scratchpad default window size

### ISSUE THREAD

**Issue by ethelack** [cococry/Ragnar#12]
Thank you Cococry for including scratchpads in such a short period of time. It's great that an unlimited number of scratchpad counts can be defined by users in the config.h file.

On my 1920x1080 display the scratchpads open in size 964x532. I am finding this size a bit too small to display mc, btop and links browser for reading files locally.

I know I can resize the scratchpad window with a right click/drag of the mouse but would prefer it if the scratchpads opened by default in a larger size about 1600x900.

Have looked thru ragnar.c for lines to change the size of the scratchpad but have not found how to do this.

Is it possible you could add a feature in config.h where the size of the scratchpad windows can be defined.

If its too difficult to code just leave it as is I'm just delighted you've added scratchpads that can be used so easily.

**Comment by cococry** [comment]
yes it is possible. you have to start your terminal with a size parameter. for alacritty it would be:

'-o window.dimensions.columns=*something* -o window.dimensions.lines=*something*'

This should set your scratchpad to your desired size :)

**Comment by ethelack** [comment]
Didn't realise scratchpads could do that, alacritty sizes are perfect now.

Also I noticed from the latest ragnar updates the scratchpads now open by default as size 1470x750 so thanks for the  modification.
