### ISSUE TITLE
unable to load ft2build.h

### ISSUE THREAD

**Issue by meliodas0n** [cococry/Ragnar#2]
I am trying to install this on Ubuntu 23.04, I am getting the following error when doing "sudo make clean install"

~/Ragnar$ sudo make clean install
rm -f ragnar
rm -f /usr/bin/ragnar
gcc ragnar.c -o ragnar -lX11 -lXcursor -lXft -O3 -ffast-math -Wall -Wextra
In file included from ragnar.c:4:
/usr/include/X11/Xft/Xft.h:40:10: fatal error: ft2build.h: No such file or directory
   40 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2: install] Error 1

The libfreetype dev package is already installed yet this is unable to load it.
How can I resolve this ?

**Comment by cococry** [comment]
type cp /usr/include/freetype2/* /usr/include 

this should resolve the issue

**Comment by MitchRatquest** [comment]
I added "-L /usr/include/freetype2"  to the Makefile to build it on Debian 11:
```
install:
	gcc ragnar.c -o ragnar -I/usr/include/freetype2 -lX11 -lXcursor -lXft -O3 -ffast-math -Wall -Wextra
	cp ragnar /usr/bin/ragnar
```

**Comment by meliodas0n** [comment]
> type cp /usr/include/freetype2/* /usr/include
> 
> this should resolve the issue

thanks, this has fixed the issue.
