### ISSUE TITLE
Arch Linux AUR Package

### ISSUE THREAD

**Issue by Luxzi** [cococry/Ragnar#20]
I've created a PKGBUILD for Ragnar. I haven't done much testing since it's two in the morning for me, but it should get the job done. If there are any issues I will fix them tomorrow.

**Code here**
https://github.com/Luxzi/ragnar-pkgbuild

**Comment by cococry** [comment]
thanks a lot! i will look at it asap. 

appreciate the great work!

**Comment by cococry** [comment]
could you open a pr if it's done?

**Comment by Luxzi** [comment]
I haven't tested for bugs yet, but since I just woke up I'm going to do some quick VM testing to make sure it installs without issue. I would also like to add that you could add this to the repo but more likely this should just be on the AUR itself that way people can just use an AUR helper tool (such as yay) to install it without hassle. I will create a PR when I am finished testing it.

**Comment by Luxzi** [comment]
**Update:**

It installs the files into the right places, I haven't got Xorg to actually start it. Working on it.

**Comment by Luxzi** [comment]
Unless you want me to maintain the AUR package.
This is how you upload the the package to the AUR.

https://wiki.archlinux.org/title/AUR_submission_guidelines

**Comment by cococry** [comment]
i merged it

**Comment by Luxzi** [comment]
Are you planning on putting it on the AUR? That was why I made it.

**Comment by cococry** [comment]
i put the PKGBUILD on the AUR under the package name ragnarwm now. Thanks very much again for the PKGBUILD :D

**Comment by Luxzi** [comment]
No problem :)
