### ISSUE TITLE
Windows do not fit screen on non-16:9 resolutions

### ISSUE THREAD

**Issue by Luxzi** [cococry/Ragnar#21]
**Expected behavior:**
The windows will fit the resolution. The bar is on top of the windows.

**Actual Behavior:**
The windows only fit 16:9 resolutions. The bar is not in the correct place.

**To Reproduce:**
1. Start Ragnar on a display with a non-16:9 resolution or use xrandr to change the resolution to a non-16:9 one
2. Windows will no longer fit the screen and the bar will no longer be in the right place

**Screenshots:**

2560x1080 21:9 Ultra-wide monitor
![](https://i.imgur.com/S88ZsJv.png)

 - OS: Arch Linux
 - Version: 1.3

**Comment by cococry** [comment]
did you change the monitor setup in the config?

**Comment by Luxzi** [comment]
Where and what would I have to change?

**Comment by cococry** [comment]
change the monitor layout in the config it is called Monitor Monitors[]. You can give a width and height to your monitors there and adjust the count of your monitors
