### ISSUE TITLE
The WM glitches/bugs out

### ISSUE THREAD

**Issue by Poyso** [cococry/Ragnar#34]
https://github.com/cococry/Ragnar/assets/72195084/ae8cd5d2-d92d-497c-bee6-8657ec8f674b

As you can see when i play around with the wm sometimes it bugs (more precisely when i close windows and i think even when i open them). The same happened yesterday with the ver 1.3 ( i think was even worse the state). I want to figure out if the problem is the VIrtual Machine itself or something else. 
Keep in mind that this is a fresh arch installation with basically only the dependencies and xorg.

**Desktop**
 - OS: Arch Linux
 - Host: Virtual Box

**Comment by cococry** [comment]
should be fixed with the last commit

**Comment by Poyso** [comment]
ok now it works ty
