### ISSUE TITLE
Ragnar doesn't work on Linux Mint

### ISSUE THREAD

**Issue by Voluptua** [cococry/ragnar#39]
**Describe the bug**
When I log in, the screen is just black and the only thing you can do is to move the cursor around.

**To Reproduce**
1. Install Mint
2. Install Ragnar
3. Log on in RagnarWM

**Desktop (please complete the following information):**
 - Linux Mint

I don't know if Ragnar is compatible with other distros such as mint or pop os but since Mint is Ubuntu based, I thought that it would work flawlessly, but that isnt the case. Any help would be appreciated.

**Comment by FableDarkside00** [comment]
I'm with same issue on Debian 12.5 I've made a clean installation cause I wanted to set Ragnar as my main manager with a clean system, but I've got a bunch of errors together the black screen.

**Comment by MubinMuhammad** [comment]
It's a default behaviour for ragnar, you have to look at the `config.h`. In there, make sure to set the MONITOR_COUNT macro & Monitors struct to your monitor's configuration. And have a look at the config in general, to see what other packages you may need.

**Comment by OfficialPixelBrush** [comment]
It immediately crashes the moment I click anything lol
