### ISSUE TITLE
Bug when starting ragnar

### ISSUE THREAD

**Issue by Blackneeed** [cococry/ragnar#46]
**Describe the bug**
While starting ragnar, on a 5120x1440 screen (dont know if that matters, but the ragbar positioning seems bad)
I get these errors: (see image)

**To Reproduce**
Follow the tutorial, get into TTY and run xinit

**Expected behavior**
Ragnar should start.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arco Linux
 - Browser firefox (do not know why that matters)
 - Version ArcoLinuXS![image](https://github.com/cococry/ragnar/assets/121721929/ed963db6-5695-46cf-b339-f02abcbb8aee)

**Comment by Blackneeed** [comment]
@cococry

**Comment by Blackneeed** [comment]
Wait, is there something in config.h

**Comment by cococry** [comment]
try 
git checkout c2e1c529505439493090ad8fb7ccca4dfdc5f5a2

And in the config.h, configure your monitor setup. This should fix it

**Comment by Blackneeed** [comment]
Will try, thx

**Comment by Blackneeed** [comment]
It worked, but the buttons (terminal, web, search) are not entirely on the right, in fact everything on the bar is positioned as if its FHD.

**Comment by Blackneeed** [comment]
Okay, im going to check that out
