### ISSUE TITLE
Cant start Ragnar

### ISSUE THREAD

**Issue by J-onasJones** [cococry/Ragnar#6]
**Describe the bug**
This is probably not a bug and more incompetence on my side but I am unable to start the WM. The `.xinitrc` file didnt exist before I created it and added `exec ragnar` to it. I am using Gdm and Xorg if that helps

**To Reproduce**
1. boot pc
2. tried multiple ways of starting Ragnar like manually running `ragnar open` and `exec ragnar` in tty with error `ragnar: Keyfile not found` or the shell just closing and reprompting me for login
**Expected behavior**
Ragnar starts

**Desktop (please complete the following information):**
 - OS: ArchLinux Kernel 6.3.2-arch1-1
 - Browser Firefox
 - Version Ragnar V1.0

**Comment by burein-ita** [comment]
Ragnar expects you to use _xinit_

On Arch _xinit_ is provided by the _xorg-xinit_ package
`sudo pacman -S xorg-xinit`

Then according to the **README** in your ~/.xinitrc add:
`exec ragnar`

Finally just run
`startx`

More info:
[https://wiki.archlinux.org/title/Xinit](url)

**Comment by cococry** [comment]
First, install all dependencies like in the README. Then you have to create a .xinitrc file in your home directory. Put "exec ragnar" in there. Then you have to execute the startx command in a tty. 

This should work.

**Comment by ethelack** [comment]
If I am not mistaken the display manager gdm reads the file ~/.xsession after login which is selected by the session type named "custom". This differs from ~/.xinitrc which is executed by xinit invoked by the startx command from the user's terminal login shell.

solution:
cp ~/.xinitrc ~/.xsession
Select "custom" for session type in gdm.

**Comment by J-onasJones** [comment]
thanks, for the quick replies. I had used the `ragnar-git` package from the arch AUR which seems to not be working for me. After cloning the repo manually and running the make command, I get similar results. Running `sudo xinit` and `exec ragnar` in tty I get a black screen with a single white box containing the lign of text with user and hostname, presumably the terminal which I am unable to type in as it is not focused. I have no mouse pointer either. Is there perhaps something im missing in the config file? I did manage to (sort of) start ragnar in an already running desktop environment with every component of ragnar showing up in a different window with actual top bar and colors and all.

**Comment by cococry** [comment]
starting xinit with sudo causes this behavior. try calling just "startx" or just "xinit". this should work.

**Comment by J-onasJones** [comment]
so startx actually, works, thanks! xinit without sudo still returns an error. Now I need to adjust the config file to account for my 4k monitor and some other customisation but the top bar is now fully visible, thanks so much!

**Comment by cococry** [comment]
perfect! you're welcome :)
