### ISSUE TITLE
xorg-dev not found

### ISSUE THREAD

**Issue by JuanH88** [cococry/Ragnar#8]
i ran the script, it gives me an error: xorg-dev package not found, at the end it says ragnar installed, but i don't have any entry in my display manager (gdm)

**Comment by cococry** [comment]
fixed installation file. should now work

**Comment by JuanH88** [comment]
I fixed it recently with xserver-xorg-devel, several packages from the xorg group were installed, but still no entries in gdm

**Comment by cococry** [comment]
yes. you need to rerun the installation script with curl. This will run the new updated script

**Comment by JuanH88** [comment]
Now it throws me this error, cp: can't create regular file 'usr/sharexsessions/ragnar.desktop': file or directory does not exist

**Comment by cococry** [comment]
this is now fixed again. rerun the script

**Comment by JuanH88** [comment]
Correct, I already have the input in gdm.  As a suggestion, you could add the --needed parameter to the script to avoid reinstalling packages. Thanks!

**Comment by JuanH88** [comment]
Sorry to bother, but I just restarted and the ragnar session does not load, I only see the mouse and the screen is black

**Comment by cococry** [comment]
yes this is normal. install alacritty to your machine as its the default terminal. then just press super + Enter and your terminal should come up. the screen is black because you have no wallpaper set.

**Comment by JuanH88** [comment]
I think I have problems with the font, the icons are not seen as in the image and if I use dmenu then it does not let me write in the applications that I launch

**Comment by JuanH88** [comment]
I could add ttf-jetbrains-mono-nerd in the script or put it in the readme.md for clueless people like me😅
